server:
  port: 9990
spring:
  datasource:
    url: jdbc:mysql://samat-server/iepg?characterEncoding=utf8
    username: root
    password: salam
    validationQuery: SELECT 1
    testOnBorrow: true

  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none

flyway:
  enabled: true
  baselineOnMigrate: true

